-- 코드를 입력하세요
SELECT 
    FOOD_PRODUCT.PRODUCT_ID AS PRODUCT_ID, 
    FOOD_PRODUCT.PRODUCT_NAME AS PRODUCT_NAME,
    FOOD_PRODUCT.PRICE * SUM(FOOD_ORDER .AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT 
JOIN FOOD_ORDER ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE YEAR(FOOD_ORDER .PRODUCE_DATE) = 2022 
    AND MONTH(FOOD_ORDER .PRODUCE_DATE) = 5
GROUP BY FOOD_PRODUCT.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
