-- 코드를 입력하세요
SELECT 
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM (SELECT CATEGORY, PRODUCT_ID, PRICE, PRODUCT_NAME,
        RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
      FROM FOOD_PRODUCT 
      WHERE CATEGORY IN ('과자', '국', '김치', '식용유')) RANKING
WHERE RNK = 1
ORDER BY PRICE DESC;