-- 코드를 작성해주세요
SELECT 
    COUNT(*) AS FISH_COUNT,
    NAME.FISH_NAME AS FISH_NAME
FROM FISH_NAME_INFO AS NAME
JOIN FISH_INFO AS INFO ON INFO.FISH_TYPE = NAME.FISH_TYPE
GROUP BY NAME.FISH_NAME
ORDER BY FISH_COUNT DESC;
