-- 코드를 작성해주세요
SELECT 
    SUB_TABLE.QUERY_KEY AS YEAR,
    (SUB_TABLE.MAX_SIZE - ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV,
    ECOLI_DATA.ID AS ID
FROM ECOLI_DATA
JOIN (SELECT 
        YEAR(DIFFERENTIATION_DATE) AS QUERY_KEY,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
      FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)) SUB_TABLE
ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = SUB_TABLE.QUERY_KEY
ORDER BY YEAR ASC, YEAR_DEV ASC;