-- 코드를 작성해주세요
SELECT
    CONCAT(
        ROW_NUMBER() OVER (ORDER BY GROUP_KEY ASC), 'Q'
    ) AS QUARTER,
    ECOLI_COUNT
FROM (
    SELECT 
        FLOOR((MONTH(DIFFERENTIATION_DATE) - 1) / 3) AS GROUP_KEY, 
        COUNT(*) AS ECOLI_COUNT
    FROM ECOLI_DATA
    GROUP BY FLOOR((MONTH(DIFFERENTIATION_DATE) - 1) / 3)
) SUB_GROUP;