-- 코드를 입력하세요
SELECT
    YEAR(ONLINE_SALE.SALES_DATE) AS YEAR,
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH,
    COUNT(DISTINCT ONLINE_SALE.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT ONLINE_SALE.USER_ID) / NULLIF((
            SELECT COUNT(*) 
            FROM USER_INFO ui
            WHERE YEAR(ui.JOINED) = 2021
        ), 0), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE 
JOIN USER_INFO ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
WHERE ONLINE_SALE.USER_ID IN (SELECT USER_ID FROM USER_INFO 
                              WHERE YEAR(JOINED) = 2021)
GROUP BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;