-- 코드를 입력하세요
SELECT 
    CONCAT('/home/grep/src/', USED_GOODS_FILE.BOARD_ID, '/', USED_GOODS_FILE.FILE_ID, USED_GOODS_FILE.FILE_NAME,USED_GOODS_FILE.FILE_EXT) AS FILE_PATH
FROM (SELECT
        BOARD_ID, 
        RANK() OVER(ORDER BY `VIEWS` DESC) AS RNK    
      FROM USED_GOODS_BOARD) T
JOIN USED_GOODS_FILE ON T.BOARD_ID = USED_GOODS_FILE.BOARD_ID
WHERE T.RNK = 1
ORDER BY USED_GOODS_FILE.FILE_ID DESC;
