-- 코드를 입력하세요
SELECT 
    APPOINTMENT.APNT_NO AS APNT_NO,
    PATIENT.PT_NAME AS PT_NAME,
    APPOINTMENT.PT_NO AS PT_NO, 
    APPOINTMENT.MCDP_CD AS MCDP_CD, 
    DOCTOR.DR_NAME AS DR_NAME,
    APPOINTMENT.APNT_YMD AS APNT_YMD
FROM APPOINTMENT 
JOIN PATIENT ON APPOINTMENT.PT_NO = PATIENT.PT_NO
JOIN DOCTOR ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
    AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC;
