-- 코드를 작성해주세요
SELECT 
    HR_DEPARTMENT.DEPT_ID AS DEPT_ID,
    HR_DEPARTMENT.DEPT_NAME_EN AS DEPT_NAME_EN,
    ROUND(AVG(HR_EMPLOYEES.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT
JOIN HR_EMPLOYEES ON HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
GROUP BY HR_DEPARTMENT.DEPT_ID
ORDER BY AVG_SAL DESC;