-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
        RANK() OVER (PARTITION BY FOOD_TYPE
                     ORDER BY FAVORITES DESC) RNK
      FROM REST_INFO) T
WHERE RNK = 1
ORDER BY FOOD_TYPE DESC;