-- 코드를 입력하세요
SELECT
    USED_GOODS_USER.USER_ID,
    USED_GOODS_USER.NICKNAME,
    SUB_TABLE.TOTAL_SALES AS TOTAL_SALES
FROM USED_GOODS_USER
JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
      FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID) SUB_TABLE
ON USED_GOODS_USER.USER_ID = SUB_TABLE.WRITER_ID
WHERE SUB_TABLE.TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;
