-- 코드를 입력하세요
SELECT 
    ANIMAL_INS.ANIMAL_ID AS ANIMAL_ID,
    ANIMAL_INS.NAME AS NAME
FROM ANIMAL_OUTS
JOIN ANIMAL_INS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME DESC
LIMIT 2;